### PR TITLE
Fix Windows start of background process

### PR DESCRIPTION
**Pull request by mlocati**
I still have to configure my environment in order to have a running websocket service (do you have a very simple example from A to Z?), but this should work.

### CODE REVIEW

**Comment by marcokuoni** [comment]
What do you mean with configure? the apache proxies or the C5 configs?

I need to add the proxies but afterwards i can start the websocket server and configure it from /index.php/dashboard/system/environment/graphql Is this not working for you?

**Comment by marcokuoni** [comment]
But i think after installing the package we are working here and this https://github.com/lemonbrain-mk/graphql_websocket_sample you just can go to /index.php/dashboard/system/environment/graphql click "Refresh GraphQL Schema" then you should have the possiblity to put websocket server to on -> click save -> click "start this websocket server"

**Review by marcokuoni — APPROVED** [review]
This looks good.

**Comment by mlocati** [comment]
> What do you mean with configure? the apache proxies or the C5 configs?

I needed a sample application, and https://github.com/lemonbrain-mk/graphql_websocket_sample looks perfect! Thanks!!

**Comment by mlocati** [comment]
I just tested this package on Windows (with youre sample package), and everything works fine!

**Comment by marcokuoni** [comment]
Amazing: Thanks a lot for your effort. On the concrete5 slack I also created a channel for discussion #graphql_api_websocket . At the moment, i have really a lot to do, but we created the first real life project with it and i'm looking forward to work more with this package,

**Pull request merged**
